name: ServerChannelChat
version: '0.0.2'
main: com.mcgendai.chat.serverChannelChat.ServerChannelChatPaper
api-version: '1.21'
authors: [ Rei0925 ]
website: https://chat.mcgendai.com
permissions:
  scc.ngword:
    description: NG系全権限
  scc.ngword.add:
    description:
  scc.ngword.del:
    description:
  scc.ngword.list:
    description:
  scc.ngword.search:
    description:
